services:
  django:
    build: .
    container_name: taskflow-django
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
      - static_data:/app/staticfiles
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - rabbitmq

  notification_service:
    build:
      context: ./notification_service
    container_name: taskflow-notifications
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - rabbitmq

  nginx:
    image: nginx:1.27-alpine
    container_name: taskflow-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_data:/static:ro
    depends_on:
      - django
      - notification_service

  postgres:
    image: postgres:16
    container_name: taskflow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: taskflow-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: taskflow-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}

volumes:
  postgres_data:
  redis_data:
  static_data:
