[mypy]
python_version = 3.12
warn_unused_configs = True

[mypy-django.*]
ignore_missing_imports = True

[mypy-channels.*]
ignore_missing_imports = True

[mypy-rest_framework_simplejwt.*]
ignore_missing_imports = True

[mypy-apps.*.models]
disallow_subclassing_any = False

[mypy-apps.*.apps]
disallow_subclassing_any = False

[mypy-apps.realtime.routing]
disallow_subclassing_any = False

[mypy-apps.realtime.consumers]
disable_error_code = misc

[mypy-apps.tasks.signals]
disable_error_code = untyped-decorator
